apiVersion: apps/v1
kind: Deployment
metadata:
  name: aai
  namespace: aai
  labels:
    app: aai
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aai
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aai
    spec:
      containers:
        - env:
            - name: AAI_DEFAULT_WEGAS_ROOT
              value: {{ .Values.aai.default_root }}
            - name: AAI_SECRET
              value: {{ .Values.aai.secret }}
            - name: AAI_SERVER_NAME
              value: {{ .Values.ingress.host }}
            - name: AAI_SERVER_PORT
              value: {{ .Values.ingress.server_port | quote }}
            - name: AAI_TLS_VERIFY_PEER
              value: "true"
            - name: AAI_DOMAIN_WHITELIST
              value: {{ .Values.aai.domain_whitelist }}
            - name: AAI_ENTITY_ID
              value: https://{{ .Values.ingress.host }}/shibboleth
          image: {{ .Values.image }}
          imagePullPolicy: Always
          name: aai
          resources:
            requests:
              memory: 100Mi
              cpu: 256m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
#            capabilities:
#              add:
#                - NET_BIND_SERVICE
#                - SYS_ADMIN
#              drop:
#                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /etc/shibboleth/sp-key.pem
              name: aai
              subPath: sp-key.pem
            - mountPath: /etc/shibboleth/sp-cert.pem
              name: aai
              subPath: sp-cert.pem
            - mountPath: /etc/shibboleth/shibboleth2.xml
              name: aai
              subPath: shibboleth2.xml
            - mountPath: /etc/shibboleth/security-policy.xml
              name: aai
              subPath: security-policy.xml
            - mountPath: /etc/shibboleth/SWITCHaaiRootCA.crt.pem
              name: aai
              subPath: SWITCHaaiRootCA.crt.pem
      imagePullSecrets:
        - name: {{ .Values.pull_secret }}
      volumes:
        - name: aai
          configMap:
            name: aai
            defaultMode: 0644