{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: aai
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: aai
  namespace: aai
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #haproxy-ingress.github.io/backend-protocol: "h1-ssl"
    #kubernetes.io/ingress.class: haproxy
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host }}-tls
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: aai
                port:
                  number: {{ .Values.ingress.server_port }}
            pathType: ImplementationSpecific
{{- end }}