apiVersion: v1
data:
  GITHUB_ADMIN_TOKEN: {{ .Values.github.admin_token | b64enc }}
  GITHUB_APP_SECRET: {{ .Values.github.app_secret | b64enc }}
  RANCHER_TOKEN: {{ .Values.rancher.token | b64enc }}
  ADMIN_TOKEN: {{ .Values.admin.token | b64enc }}
kind: Secret
metadata:
  name: {{ template "wwm.fullname" . }}-secret
  labels:
    app: {{ template "wwm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque

