apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ template "wegas.fullname" . }}-registry
stringData:
  .dockerconfigjson: |-
    {
       "auths": {
           "{{- .Values.registry.host  -}}": {
               "auth": "{{- .Values.registry.token | b64enc -}}"
           }
       }
    }
