apiVersion: v2
name: wegas-war-manager
description: Wegas War Manager Rancher Chart
icon: https://raw.githubusercontent.com/Heigvd/Wegas/master/wegas-app/src/main/webapp/favicon_pink.png
type: application
version: 0.1.0
appVersion: 1.0.0
