{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "wegas.fullname" . }}
  labels:
    app: {{ template "wegas.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    #traefik.ingress.kubernetes.io/max-conn-amount: {{ .Values.wegas.nbthreads | quote }}
    #traefik.ingress.kubernetes.io/max-conn-extractor-func: request.host
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.hostname }}-tls
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            port:
              number: 8080
            name: {{ template "wegas.fullname" . }}
{{- end -}}
