apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wegas.fullname" . }}-mongo
  generation: 1
  labels:
    app: {{ template "wegas.fullname" . }}-mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "wegas.fullname" . }}-mongo
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "wegas.fullname" . }}-mongo
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ template "wegas.fullname" . }}-mongo
          image: mongo:4.4
          args:
          - --enableMajorityReadConcern
          imagePullPolicy: Always
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 1
            periodSeconds: 2
            successThreshold: 2
            tcpSocket:
              port: 27017
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: {{ if .Values.mongo.useExistingClaim -}}{{- .Values.mongo.existingClaim -}} {{- else -}} {{- template "wegas.fullname" . -}}-mongo-pvc {{- end }}
