apiVersion: v1
kind: Service
metadata:
  name: {{ template "wegas.fullname" . }}-internal
  labels:
    app: {{ template "wegas.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 443
      protocol: TCP
      name: https
      targetPort: 443
    - port: 80
      protocol: TCP
      name: http
      targetPort: 80
  selector:
    app: {{ template "wegas.fullname" . }}-payara
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "wegas.fullname" . }}
  labels:
    app: {{ template "wegas.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      name: https
      targetPort: 443
    - port: 80
      protocol: TCP
      name: http
      targetPort: 80
  selector:
    app: {{ template "wegas.fullname" . }}-payara
    release: {{ .Release.Name }}

