{{- if not .Values.db.useExistingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "wegas.fullname" . }}-psql-pvc
  labels:
    app: {{ template "wegas.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.size | quote }}
  storageClassName: ceph-ssd-retain
{{ end }}

