apiVersion: v1
data:
    S3_backup_key: {{ .Values.backup.s3.key | b64enc }}
    S3_backup_secret: {{ .Values.backup.s3.secret | b64enc }}
    backup_encryption_password: {{ .Values.backup.s3.backup_encryption_password | b64enc }}
kind: Secret
metadata:
  name: {{ template "gb.fullname" . }}-backup-secret
  labels:
    app: {{ template "gb.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
data:
  .dockerconfigjson: {{ .Values.backup.pull_secret }}
type: kubernetes.io/dockerconfigjson

