apiVersion: v1
kind: ConfigMap
data:
  DB_USER: {{ .Values.db.user }}
  DB_NAME: {{ .Values.db.name }}
  BRANCH: {{ .Values.wegas.type -}}-{{- .Values.wegas.name }}
  JAVA_HEAP: {{ .Values.wegas.java_heap }}M
  NB_POPULATORS: {{ .Values.wegas.nbpopulators | quote }}
  NB_THREADS: {{ .Values.wegas.nbthreads | quote }}
metadata:
  name: {{ template "wegas.fullname" . }}-config
  labels:
    app: {{ template "wegas.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
