apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ll.fullname" . }}-api
  labels:
    app: {{ template "ll.fullname" . }}-api-deployment
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "ll.fullname" . }}-api-pod
  template:
    metadata:
      labels:
        app: {{ template "ll.fullname" . }}-api-pod
    spec:
      containers:
      - image: ghcr.io/heigvd/ll/api
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ template "ll.fullname" . -}}-config
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: {{ template "ll.fullname" . }}-api-pod
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
#          limits:
#            memory: 500Mi
#            cpu: 200m
