{{- if .Values.backup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "ll.fullname" . }}-backup-cronjob
  labels:
    app: {{ template "ll.fullname" . }}-backup-cronjob
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  suspend: {{ .Values.backup.suspend }}
  schedule: "30 23 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      backoffLimit: 1
      template:
        spec:
          containers:
            - env:
              - name: RCLONE_CONFIG_BACKUP_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: S3_backup_key
                    name: {{ template "ll.fullname" . }}-backup-secret
              - name: RCLONE_CONFIG_BACKUP_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: S3_backup_secret
                    name: {{ template "ll.fullname" . }}-backup-secret
              - name: ALBASIM_APP_BACKUP_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "ll.fullname" . }}-backup-configmap
                    key: backup_bucket
              - name: RCLONE_CONFIG_BACKUP_TYPE
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "ll.fullname" . }}-backup-configmap
                    key: rclone_type
              - name: RCLONE_CONFIG_BACKUP_ENV_AUTH
                value: "false"
              - name: RCLONE_CONFIG_BACKUP_PROVIDER
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "ll.fullname" . }}-backup-configmap
                    key: rclone_provider
              - name: RCLONE_CONFIG_BACKUP_ENDPOINT
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "ll.fullname" . }}-backup-configmap
                    key: rclone_endpoint
              - name: RCLONE_CONFIG_BACKUP_ACL
                value: private
              - name: MONGO_DB
                value: learninglocker_v2
              - name: MONGO_HOST
                value: {{ template "ll.fullname" . }}-mongo-service
              - name: ALBASIM_APP_BACKUP_ENCRYPTION_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: backup_encryption_password
                    name: {{ template "ll.fullname" . }}-backup-secret
                    optional: false
              image: 'ghcr.io/heigvd/backup-cronjob-mongo34:1.0.0'
              name: backup-cronjob
              imagePullPolicy: Always
              command: ["/run_backup_mongo.sh"]
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ghcr-pull-secret
  {{ end }}