{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
  name: ll-ui
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: /data/xAPI
          pathType: Prefix
          backend:
            service:
              name: {{ template "ll.fullname" . }}-xapi-service
              port:
                number: 8081
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ template "ll.fullname" . }}-ui-service
              port:
                number: 3000
{{- end -}}
