{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password | default "" | quote }}
metadata:
  name: {{ template "wegas.fullname" . }}-secret
  labels:
    app: {{ template "wegas.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
