backup:
  enabled: false
  suspend: false
  pull_secret:
  s3:
    key:
    secret:
    bucket:
    rclone_type:
    rclone_provider:
    rclone_endpoint:
    backup_encryption_password:
    pvc_name:
